package builder

import entity.ElementNode
import entity.TextNode
import shared.Attribute
import shared.AttributeName
import shared.Tags

fun html(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit): HTMLBuilder {
    val builder = HTMLBuilder()
    builder.create(attributes.toMutableList())
    builder.block()
    return builder
}

infix fun AttributeName.to(value: String) = Attribute(this, value)

fun HTMLBuilder.tag(tag: Tags, block: HTMLBuilder.() -> Unit = {}, attributes: Array<out Attribute>) {
    val node = ElementNode(tag, attributes.toMutableList())
    this.append(node)
    this.enter(node)
    this.block()
    this.pop()
}

fun HTMLBuilder.text(content: String) {
    this.append(TextNode(content))
}

fun HTMLBuilder.a(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.A, block, attributes)
fun HTMLBuilder.abbr(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.ABBR, block, attributes)
fun HTMLBuilder.address(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.ADDRESS, block, attributes)
fun HTMLBuilder.area(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.AREA, block, attributes)
fun HTMLBuilder.article(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.ARTICLE, block, attributes)
fun HTMLBuilder.aside(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.ASIDE, block, attributes)
fun HTMLBuilder.studio(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.AUDIO, block, attributes)
fun HTMLBuilder.b(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.B, block, attributes)
fun HTMLBuilder.base(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.BASE, block, attributes)
fun HTMLBuilder.bdi(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.BDI, block, attributes)
fun HTMLBuilder.bdo(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.BDO, block, attributes)
fun HTMLBuilder.blockquote(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.BLOCKQUOTE, block, attributes)
fun HTMLBuilder.body(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.BODY, block, attributes)
fun HTMLBuilder.br(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.BR, block, attributes)
fun HTMLBuilder.button(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.BUTTON, block, attributes)
fun HTMLBuilder.canvas(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.CANVAS, block, attributes)
fun HTMLBuilder.caption(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.CAPTION, block, attributes)
fun HTMLBuilder.cite(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.CITE, block, attributes)
fun HTMLBuilder.code(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.CODE, block, attributes)
fun HTMLBuilder.col(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.COL, block, attributes)
fun HTMLBuilder.colgroup(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.COLGROUP, block, attributes)
fun HTMLBuilder.data(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.DATA, block, attributes)
fun HTMLBuilder.datalist(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.DATALIST, block, attributes)
fun HTMLBuilder.dd(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.DD, block, attributes)
fun HTMLBuilder.del(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.DEL, block, attributes)
fun HTMLBuilder.details(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.DETAILS, block, attributes)
fun HTMLBuilder.dfn(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.DFN, block, attributes)
fun HTMLBuilder.dialog(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.DIALOG, block, attributes)
fun HTMLBuilder.div(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.DIV, block, attributes)
fun HTMLBuilder.dl(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.DL, block, attributes)
fun HTMLBuilder.dt(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.DT, block, attributes)
fun HTMLBuilder.em(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.EM, block, attributes)
fun HTMLBuilder.embed(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.EMBED, block, attributes)
fun HTMLBuilder.fieldset(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.FIELDSET, block, attributes)
fun HTMLBuilder.figcaption(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.FIGCAPTION, block, attributes)
fun HTMLBuilder.figure(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.FIGURE, block, attributes)
fun HTMLBuilder.footer(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.FOOTER, block, attributes)
fun HTMLBuilder.form(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.FORM, block, attributes)
fun HTMLBuilder.h1(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.H1, block, attributes)
fun HTMLBuilder.h2(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.H2, block, attributes)
fun HTMLBuilder.h3(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.H3, block, attributes)
fun HTMLBuilder.h4(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.H4, block, attributes)
fun HTMLBuilder.h5(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.H5, block, attributes)
fun HTMLBuilder.h6(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.H6, block, attributes)
fun HTMLBuilder.head(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.HEAD, block, attributes)
fun HTMLBuilder.header(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.HEADER, block, attributes)
fun HTMLBuilder.hgroup(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.HGROUP, block, attributes)
fun HTMLBuilder.hr(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.HR, block, attributes)
fun HTMLBuilder.i(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.I, block, attributes)
fun HTMLBuilder.iframe(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.IFRAME, block, attributes)
fun HTMLBuilder.img(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.IMG, block, attributes)
fun HTMLBuilder.input(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.INPUT, block, attributes)
fun HTMLBuilder.ins(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.INS, block, attributes)
fun HTMLBuilder.kbd(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.KBD, block, attributes)
fun HTMLBuilder.label(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.LABEL, block, attributes)
fun HTMLBuilder.legend(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.LEGEND, block, attributes)
fun HTMLBuilder.li(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.LI, block, attributes)
fun HTMLBuilder.link(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.LINK, block, attributes)
fun HTMLBuilder.main(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.MAIN, block, attributes)
fun HTMLBuilder.map(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.MAP, block, attributes)
fun HTMLBuilder.mark(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.MARK, block, attributes)
fun HTMLBuilder.menu(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.MENU, block, attributes)
fun HTMLBuilder.meta(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.META, block, attributes)
fun HTMLBuilder.meter(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.METER, block, attributes)
fun HTMLBuilder.nav(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.NAV, block, attributes)
fun HTMLBuilder.noscript(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.NOSCRIPT, block, attributes)
fun HTMLBuilder.objectT(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.OBJECT, block, attributes)
fun HTMLBuilder.ol(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.OL, block, attributes)
fun HTMLBuilder.optgroup(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.OPTGROUP, block, attributes)
fun HTMLBuilder.option(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.OPTION, block, attributes)
fun HTMLBuilder.output(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.OUTPUT, block, attributes)
fun HTMLBuilder.p(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.P, block, attributes)
fun HTMLBuilder.picture(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.PICTURE, block, attributes)
fun HTMLBuilder.pre(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.PRE, block, attributes)
fun HTMLBuilder.progress(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.PROGRESS, block, attributes)
fun HTMLBuilder.q(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.Q, block, attributes)
fun HTMLBuilder.rp(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.RP, block, attributes)
fun HTMLBuilder.rt(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.RT, block, attributes)
fun HTMLBuilder.ruby(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.RUBY, block, attributes)
fun HTMLBuilder.s(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.S, block, attributes)
fun HTMLBuilder.samp(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.SAMP, block, attributes)
fun HTMLBuilder.script(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.SCRIPT, block, attributes)
fun HTMLBuilder.search(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.SEARCH, block, attributes)
fun HTMLBuilder.section(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.SECTION, block, attributes)
fun HTMLBuilder.select(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.SELECT, block, attributes)
fun HTMLBuilder.slot(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.SLOT, block, attributes)
fun HTMLBuilder.small(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.SMALL, block, attributes)
fun HTMLBuilder.source(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.SOURCE, block, attributes)
fun HTMLBuilder.span(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.SPAN, block, attributes)
fun HTMLBuilder.strong(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.STRONG, block, attributes)
fun HTMLBuilder.style(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.STYLE, block, attributes)
fun HTMLBuilder.sub(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.SUB, block, attributes)
fun HTMLBuilder.summary(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.SUMMARY, block, attributes)
fun HTMLBuilder.sup(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.SUP, block, attributes)
fun HTMLBuilder.table(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.TABLE, block, attributes)
fun HTMLBuilder.tbody(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.TBODY, block, attributes)
fun HTMLBuilder.td(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.TD, block, attributes)
fun HTMLBuilder.template(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.TEMPLATE, block, attributes)
fun HTMLBuilder.textarea(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.TEXTAREA, block, attributes)
fun HTMLBuilder.tfoot(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.TFOOT, block, attributes)
fun HTMLBuilder.th(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.TH, block, attributes)
fun HTMLBuilder.thead(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.THEAD, block, attributes)
fun HTMLBuilder.time(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.TIME, block, attributes)
fun HTMLBuilder.title(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.TITLE, block, attributes)
fun HTMLBuilder.tr(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.TR, block, attributes)
fun HTMLBuilder.track(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.TRACK, block, attributes)
fun HTMLBuilder.u(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.U, block, attributes)
fun HTMLBuilder.ul(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.UL, block, attributes)
fun HTMLBuilder.varT(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.VAR, block, attributes)
fun HTMLBuilder.video(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.VIDEO, block, attributes)
fun HTMLBuilder.wbr(vararg attributes: Attribute, block: HTMLBuilder.() -> Unit = {}) = tag(Tags.WBR, block, attributes)
