package shared

enum class Tags (val isInline: Boolean = false, val isRaw: Boolean = false) {
    A(isInline = true),
    ABBR(isInline = true),
    ADDRESS,
    AREA,
    ARTICLE,
    ASIDE,
    AUDIO,
    B(isInline = true),
    BASE,
    BDI,
    BDO(isInline = true),
    BLOCKQUOTE,
    BODY,
    BR(isInline = true),
    BUTTON(isInline = true),
    CANVAS,
    CAPTION,
    CITE(isInline = true),
    CODE(isInline = true),
    COL,
    COLGROUP,
    DATA,
    DATALIST,
    DD,
    DEL,
    DETAILS,
    DFN(isInline = true),
    DIALOG,
    DIV,
    DL,
    DT,
    EM(isInline = true),
    EMBED,
    FIELDSET,
    FIGCAPTION,
    FIGURE,
    FOOTER,
    FORM,
    H1,
    H2,
    H3,
    H4,
    H5,
    H6,
    HEAD,
    HEADER,
    HGROUP,
    HR,
    HTML,
    I(isInline = true),
    IFRAME,
    IMG(isInline = true),
    INPUT(isInline = true),
    INS,
    KBD(isInline = true),
    LABEL(isInline = true),
    LEGEND,
    LI,
    LINK,
    MAIN,
    MAP(isInline = true),
    MARK,
    MENU,
    META,
    METER,
    NAV,
    NOSCRIPT,
    OBJECT(isInline = true),
    OL,
    OPTGROUP,
    OPTION,
    OUTPUT(isInline = true),
    P,
    PICTURE,
    PRE,
    PROGRESS,
    Q(isInline = true),
    RP,
    RT,
    RUBY,
    S,
    SAMP(isInline = true),
    SCRIPT(isRaw = true),
    SEARCH,
    SECTION,
    SELECT(isInline = true),
    SLOT,
    SMALL(isInline = true),
    SOURCE,
    SPAN(isInline = true),
    STRONG(isInline = true),
    STYLE(isRaw = true),
    SUB(isInline = true),
    SUMMARY,
    SUP(isInline = true),
    TABLE,
    TBODY,
    TD,
    TEMPLATE,
    TEXTAREA(isInline = true),
    TFOOT,
    TH,
    THEAD,
    TIME(isInline = true),
    TITLE,
    TR,
    TRACK,
    U,
    UL,
    VAR(isInline = true),
    VIDEO,
    WBR
}